import React, { useState, useEffect } from 'react';
import { Globe, Search, ExternalLink, Newspaper, TrendingUp, RefreshCw } from 'lucide-react';
import { fetchMarketNews, NewsBriefing } from '../services/geminiService';
import { useAIContext } from '../contexts/AIContext';

export const MarketIntelligence: React.FC = () => {
    const { setContext } = useAIContext();
    const [query, setQuery] = useState('');
    const [briefing, setBriefing] = useState<NewsBriefing | null>(null);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        setContext('market', 'VIEW: Market Intelligence. User is researching financial news.');
        handleSearch("Global Credit Markets and Corporate Debt"); // Initial Load
    }, [setContext]);

    const handleSearch = async (term: string) => {
        setLoading(true);
        const result = await fetchMarketNews(term);
        setBriefing(result);
        setLoading(false);
    };

    return (
        <div className="p-8 max-w-7xl mx-auto min-h-screen flex flex-col">
            <div className="mb-8">
                <h1 className="text-3xl font-bold text-slate-900 flex items-center gap-3">
                    <Globe className="text-blue-600" />
                    Market Intelligence
                </h1>
                <p className="text-slate-500 mt-1">Real-time RAG (Retrieval-Augmented Generation) powered by Google Search.</p>
            </div>

            {/* Search Bar */}
            <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm mb-8">
                <form 
                    onSubmit={(e) => { e.preventDefault(); handleSearch(query); }}
                    className="flex gap-4"
                >
                    <div className="relative flex-1">
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
                        <input 
                            type="text" 
                            value={query}
                            onChange={(e) => setQuery(e.target.value)}
                            placeholder="Search for market topics (e.g., 'Tech Sector Debt', 'Eurozone Inflation')..."
                            className="w-full pl-12 pr-4 py-3 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-slate-900 bg-white"
                        />
                    </div>
                    <button 
                        type="submit"
                        disabled={loading}
                        className="bg-slate-900 text-white px-6 py-3 rounded-lg font-medium hover:bg-slate-800 transition-colors disabled:opacity-50 flex items-center gap-2"
                    >
                        {loading ? <RefreshCw className="animate-spin" /> : <Search size={18} />}
                        Analyze
                    </button>
                </form>
            </div>

            {/* Content Area */}
            {loading ? (
                <div className="flex-1 flex flex-col items-center justify-center text-slate-400 animate-pulse">
                    <div className="w-16 h-16 bg-slate-200 rounded-full mb-4"></div>
                    <div className="h-4 w-64 bg-slate-200 rounded mb-2"></div>
                    <div className="h-4 w-48 bg-slate-200 rounded"></div>
                    <p className="mt-8 text-sm">Scanning global sources via Google Search Grounding...</p>
                </div>
            ) : briefing ? (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    {/* Main Briefing */}
                    <div className="lg:col-span-2 space-y-6">
                        <div className="bg-white p-8 rounded-xl border border-blue-100 shadow-sm relative overflow-hidden">
                            <div className="absolute top-0 left-0 w-1 h-full bg-blue-500"></div>
                            <h2 className="text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
                                <TrendingUp className="text-blue-500" />
                                Executive AI Briefing
                            </h2>
                            <div className="prose prose-slate max-w-none text-slate-700 leading-relaxed">
                                <div dangerouslySetInnerHTML={{ __html: briefing.summary.replace(/\n/g, '<br/>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />
                            </div>
                            <div className="mt-6 pt-4 border-t border-slate-100 text-xs text-slate-400 flex justify-between">
                                <span>Generated by Gemini 3.5 Flash</span>
                                <span>Data verified via Google Search</span>
                            </div>
                        </div>
                    </div>

                    {/* Sources / Citations */}
                    <div className="lg:col-span-1">
                        <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Source Material</h3>
                        <div className="space-y-3">
                            {briefing.articles.length > 0 ? briefing.articles.map((article, idx) => (
                                <a 
                                    key={idx} 
                                    href={article.url} 
                                    target="_blank" 
                                    rel="noopener noreferrer"
                                    className="block p-4 bg-white border border-slate-200 rounded-lg hover:border-blue-300 hover:shadow-md transition-all group"
                                >
                                    <h4 className="font-semibold text-slate-800 text-sm mb-1 group-hover:text-blue-600 line-clamp-2">
                                        {article.title}
                                    </h4>
                                    <div className="flex items-center gap-2 text-xs text-slate-500 mt-2">
                                        <Newspaper size={12} />
                                        <span>{article.source}</span>
                                        <ExternalLink size={10} className="ml-auto opacity-0 group-hover:opacity-100 transition-opacity" />
                                    </div>
                                </a>
                            )) : (
                                <div className="text-sm text-slate-400 italic">No specific sources cited for this summary.</div>
                            )}
                        </div>
                    </div>
                </div>
            ) : (
                <div className="flex-1 flex items-center justify-center text-slate-400">
                    <p>Enter a topic to generate a market intelligence report.</p>
                </div>
            )}
        </div>
    );
};